//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyFiles.DAL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudyFiles.DAL.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert into Course ([Teacher], DisciplineID) Output Inserted.ID values (@teacher, @id).
        /// </summary>
        public static string AddCourse {
            get {
                return ResourceManager.GetString("AddCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert into Discipline ([Name], FacultyID) Output Inserted.ID values (@name, @id).
        /// </summary>
        public static string AddDiscipline {
            get {
                return ResourceManager.GetString("AddDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert into Faculty ([Name], UniversityID) Output Inserted.ID values (@name, @id).
        /// </summary>
        public static string AddFaculty {
            get {
                return ResourceManager.GetString("AddFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert into University ([Name]) Output Inserted.ID values (@name).
        /// </summary>
        public static string AddUniversity {
            get {
                return ResourceManager.GetString("AddUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select * from Course Where DisciplineID = @id.
        /// </summary>
        public static string GetCourses {
            get {
                return ResourceManager.GetString("GetCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select * from Discipline Where FacultyID = @id.
        /// </summary>
        public static string GetDisciplines {
            get {
                return ResourceManager.GetString("GetDisciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select * from Faculty Where UniversityID = @id.
        /// </summary>
        public static string GetFaculties {
            get {
                return ResourceManager.GetString("GetFaculties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select CONCAT_WS(&apos;/&apos;, U.Name, F.Name, D.Name, C.Teacher) as BreadCrumb, CONCAT_WS(&apos;\\&apos;, U.ID, F.ID, D.ID, C.ID) as Path from University as U inner join Faculty as F on(U.ID = F.UniversityID) inner join Discipline as D on(F.ID = D.FacultyID) inner join Course as C on(D.ID = C.DisciplineID) Where C.ID = @id.
        /// </summary>
        public static string GetPath {
            get {
                return ResourceManager.GetString("GetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select * from University.
        /// </summary>
        public static string GetUniversities {
            get {
                return ResourceManager.GetString("GetUniversities", resourceCulture);
            }
        }
    }
}
