//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyFiles.DAL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudyFiles.DAL.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert into Course ([Teacher], DisciplineID) Output Inserted.ID values (@teacher, @id).
        /// </summary>
        public static string AddCourse {
            get {
                return ResourceManager.GetString("AddCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert into Discipline ([Name], FacultyID) Output Inserted.ID values (@name, @id).
        /// </summary>
        public static string AddDiscipline {
            get {
                return ResourceManager.GetString("AddDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert into Faculty ([Name], UniversityID) Output Inserted.ID values (@name, @id).
        /// </summary>
        public static string AddFaculty {
            get {
                return ResourceManager.GetString("AddFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert into University ([Name]) Output Inserted.ID values (@name).
        /// </summary>
        public static string AddUniversity {
            get {
                return ResourceManager.GetString("AddUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert into Auth (Email, Login, PasswordHash, Salt, RegistrationTime) values (@email, @login, @passHash, @salt, GETDATE()).
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=localhost;Initial Catalog=StudyFiles;Integrated Security=true.
        /// </summary>
        public static string DefaultConnection {
            get {
                return ResourceManager.GetString("DefaultConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from Course where ID = @id.
        /// </summary>
        public static string DeleteCourse {
            get {
                return ResourceManager.GetString("DeleteCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from Discipline where ID = @id.
        /// </summary>
        public static string DeleteDiscipline {
            get {
                return ResourceManager.GetString("DeleteDiscipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from Faculty where ID = @id.
        /// </summary>
        public static string DeleteFaculty {
            get {
                return ResourceManager.GetString("DeleteFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from University where ID = @id.
        /// </summary>
        public static string DeleteUniversity {
            get {
                return ResourceManager.GetString("DeleteUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Auth Set Token = null Where ID = @id.
        /// </summary>
        public static string EndSession {
            get {
                return ResourceManager.GetString("EndSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select CONCAT_WS(&apos;/&apos;, U.Name, F.Name, D.Name, C.Teacher) as BreadCrumb from University as U inner join Faculty as F on(U.ID = F.UniversityID) inner join Discipline as D on(F.ID = D.FacultyID) inner join Course as C on(D.ID = C.DisciplineID) Where C.ID = @id.
        /// </summary>
        public static string GetBreadCrumb {
            get {
                return ResourceManager.GetString("GetBreadCrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select * from Course Where DisciplineID = @id.
        /// </summary>
        public static string GetCourses {
            get {
                return ResourceManager.GetString("GetCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select * from Discipline Where FacultyID = @id.
        /// </summary>
        public static string GetDisciplines {
            get {
                return ResourceManager.GetString("GetDisciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select * from Faculty Where UniversityID = @id.
        /// </summary>
        public static string GetFaculties {
            get {
                return ResourceManager.GetString("GetFaculties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select * from University.
        /// </summary>
        public static string GetUniversities {
            get {
                return ResourceManager.GetString("GetUniversities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ID, PasswordHash, Salt from Auth Where Login = @login.
        /// </summary>
        public static string GetUserData {
            get {
                return ResourceManager.GetString("GetUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ID, Login, Token from Auth Where ID = @id.
        /// </summary>
        public static string RestoreSession {
            get {
                return ResourceManager.GetString("RestoreSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Auth Set Token = @token, TokenUpdated = GETDATE() Where ID = @id.
        /// </summary>
        public static string StartSession {
            get {
                return ResourceManager.GetString("StartSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select * from Auth Where ID = @id and Token = @token.
        /// </summary>
        public static string ValidateToken {
            get {
                return ResourceManager.GetString("ValidateToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select * from Auth Where Login = @login.
        /// </summary>
        public static string VerifyUserExistence {
            get {
                return ResourceManager.GetString("VerifyUserExistence", resourceCulture);
            }
        }
    }
}
